FROM node:18-alpine3.14

USER node

RUN mkdir /home/node/code

WORKDIR /home/node/code

COPY --chown=node:node yarn.lock package.json ./

RUN yarn

COPY --chown=node:node . .

ENTRYPOINT ["npm"]

ENV TERM xterm-256color

CMD ["run","dev"]